### ISSUE TITLE
Possibilitar a criação de um template customizado.

### ISSUE THREAD

**Issue by lucaslacroix** [mateusjose/danfe-simplificada#1]
Olá.

Parabéns, muito boa a lib.

Eu estou criando um tipo de danfe pequena, diferente do template padrão, para ser impressa em uma impressora térmica.

Não seria interessante ter a possibilidade de passar o caminho de um .hbs customizado?

Desde já, obrigado!

**Comment by mateustozoni** [comment]
Opa, primeiramente obrigado!

Gostei da ideia, estava pensando em algo do tipo para realizar, vou colocar isso nas tarefas, mas caso queira fazer e criar um pull request sinta-se livre!

Abraço!

**Comment by lucaslacroix** [comment]
Ok, já estou trabalhando nisso.
